image: node:10.11.0

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g hexo-cli gulp
    - npm install
    - hexo clean
    - hexo generate
    - gulp
    - hexo deploy
  artifacts:
    paths:
      - public
  only:
    - master
