image: ubuntu:latest

services:
  - node:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  cache:
    paths:
      - node_modules/
  before_script:
    - apt-get update -y
    - apt-get install -y libpng-dev
    - npm install -g hexo-cli
  script:
    - npm install
    - sed -i -e "s/all_minifier:\ false/all_minifier:\ true/" ./_config.yml
    - hexo clean
    - hexo deploy
  artifacts:
    paths:
      - public
  only:
    - master
