image: ubuntu:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  cache:
    paths:
      - node_modules/
  before_script:
    - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
    - apt-get update -y
    - apt-get install -y build-essential nodejs libpng-dev
    - npm install -g hexo-cli
  script:
    - npm install
    - sed -i -e "s/all_minifier:\ false/all_minifier:\ true/" ./_config.yml
    - hexo clean
    - hexo deploy
  artifacts:
    paths:
      - public
  only:
    - master
