image: node:10.11.0

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  cache:
    paths:
      - node_modules/
  script:
    - sed -i -e "s/all_minifier:\ false/all_minifier:\ true/" ./_config.yml
    - npm install -g hexo-cli
    - npm install
    - hexo clean
    - hexo deploy
  artifacts:
    paths:
      - public
  only:
    - master
