image: archlinux/base

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  cache:
    paths:
      - node_modules/
  before_script:
    - pacman -Sy
    - pacman -S nodejs npm nodejs-hexo libpng
  script:
    - npm install
    - sed -i -e "s/all_minifier:\ false/all_minifier:\ true/" ./_config.yml
    - hexo clean
    - hexo deploy
  artifacts:
    paths:
      - public
  only:
    - master
