image: node:10.11.0

pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g hexo-cli
    - npm install
    - hexo deploy
  artifacts:
    paths:
      - public
  only:
    - source
