image: node:lastet

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  cache:
    paths:
      - node_modules/
  before_script:
    - export PATH=$(yarn global bin):$PATH
    - yarn global add hexo
    # - sed -i "s/LC_COUNTER_USERNAME/${LC_COUNTER_USERNAME}/" _config.yml
    # - sed -i "s/LC_COUNTER_PASSWORD/${LC_COUNTER_PASSWORD}/" _config.yml
  script:
    - yarn
    - hexo clean
    - hexo deploy
  artifacts:
    paths:
      - public
  only:
    - master
