image: node:11.1.0

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  cache:
    paths:
      - node_modules/
  before_script:
    - export PATH=$(yarn global bin):$PATH
    - yarn global add hexo
  script:
    - yarn
    - hexo clean
    - hexo deploy
  artifacts:
    paths:
      - public
  only:
    - master
