language: node_js

node_js:
  - '10'

cache:
  # apt: true
  directories:
    - node_modules

# addons:
  # apt:
    # update: true
    # packages:
      # - pandoc

before_install:
  - export TZ='Asia/Shanghai'
  - npm install hexo-cli -g
  - chmod +x ./publish.sh
  - sed -i -e "s/all_minifier:\ false/all_minifier:\ true/" ./_config.yml

install:
  - npm install

script:
  - hexo clean
  - hexo generate

after_script:
  - ./publish.sh

branches:
  only:
    source

env:
  global:
    - GH_REF: github.com/wangjiezhe/wangjiezhe.github.io
