markdown: redcarpet
permalink: /:year/:month/:title/
author: Wang Jiezhe
pygments: true
paginate: 16
url: http://wangjiezhe.github.io
timezone: 'Asia/Shanghai'
gem:
    - jemoji
    - jekyll-mentions
    - jekyll-redirect-from
