markdown: kramdown
kramdown:
    input: GFM
#redcarpet:
#    extensions:
#        - autolink
#        - strikethrough
#        - space_after_headers
#        - superscript

permalink: /:year/:month/:title/

highlighter: pygments

paginate: 16

url: http://wangjiezhe.github.io

timezone: Asia/Shanghai

encoding: utf-8

author:
    name: "Wang Jiezhe"
    url: https://twitter.com/wangjiezhe

gems:
    - jemoji
    - jekyll-mentions
    - jekyll-redirect-from
    - jekyll-sitemap

github:
    repo: https://github.com/wangjiezhe/wangjiezhe.github.io

version: 1.0.0
