# ---------------------------------------------------------------
# Theme Core Configuration Settings
# ---------------------------------------------------------------

minify: true

custom_file_path:
  #head: source/_data/head.njk
  #header: source/_data/header.njk
  sidebar: source/_data/sidebar.njk
  #postMeta: source/_data/post-meta.njk
  #postBodyEnd: source/_data/post-body-end.njk
  footer: source/_data/footer.njk
  bodyEnd: source/_data/body-end.njk
  variable: source/_data/variables.styl
  # mixin: source/_data/mixins.styl
  style: source/_data/styles.styl

# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

#language_switcher: false

footer:
  since: 2014
  icon:
    animated: true
  hosted: true

creative_commons:
  post: true
  language: deed.zh

# ---------------------------------------------------------------
# Scheme Settings
# ---------------------------------------------------------------

scheme: Gemini

darkmode: true

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

menu:
  home: / || fa fa-home
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  links: /links/ || fa fa-link

# ---------------------------------------------------------------
# Sidebar Settings
# ---------------------------------------------------------------

avatar:
  url: /images/camel.jpg
  rounded: true
  rotated: true

social:
  GitHub: https://github.com/wangjiezhe || fab fa-github
  E-Mail: mailto:wangjiezhe@gmail.com || fa fa-envelope
  Twitter: https://twitter.com/twitter || fab fa-twitter
  Telegram: https://t.me/wangjiezhe || fab fa-telegram

social_icons:
  icons_only: true
  transition: true

links_settings:
  icon: fa fa-globe
  title: 友情链接
  layout: inline

toc:
  wrap: true

# ---------------------------------------------------------------
# Post Settings
# ---------------------------------------------------------------

# symbols_count_time:
#   separated_meta: false
#   item_text_post: false

tag_icon: true

follow_me:
  WeChat: /images/wechat_channel.jpg || fab fa-weixin
  RSS: /atom.xml || fa fa-rss

related_posts:
  enable: true

# ---------------------------------------------------------------
# Custom Page Settings
# ---------------------------------------------------------------

# ---------------------------------------------------------------
# Misc Theme Settings
# ---------------------------------------------------------------

text_align:
  # Available values: start | end | left | right | center | justify | justify-all | match-parent
  desktop: justify
  mobile: start

android_chrome_color: "#66327C"

codeblock:
  theme:
    light: github-gist
    dark: atom-one-dark-reasonable
  prism:
    light: prism
    dark: prism-okaidia
  copy_button:
    enable: true
    style: mac

back2top:
  scrollpercent: true

reading_progress:
  enable: true

# ---------------------------------------------------------------
# Font Settings
# ---------------------------------------------------------------

# ---------------------------------------------------------------
# SEO Settings
# ---------------------------------------------------------------

index_with_subtitle: true

exturl: true

# ---------------------------------------------------------------
# Third Party Plugins & Services Settings
# ---------------------------------------------------------------

math:
  katex:
    enable: true
    copy_tex: true

#pjax: true

fancybox: true
#mediumzoom: true

lazyload: true

pangu: true

quicklink:
  enable: true

# ---------------------------------------------------------------
# Comments Settings
# ---------------------------------------------------------------

comments:
  # Available values: tabs | buttons
  style: tabs
  active: disqusjs
  storage: true
  lazyload: true
  # Modify texts or order for any navs, here are some examples.
  nav:
    disqusjs:
      text: Disqus
      order: 1
    utterances:
      text: Github
      order: 2
    discussbot:
      text: Telegram
      order: 3

disqusjs:
  enable: true
  api: https://disqusjs-proxy.wangjiezhe.now.sh/
  apikey: ENTX2OPfWXIYJpFIZ1WVpYt4F0Ri0PLUELMOCbM8HHIX9C9BqEbkBZWmK7lqKj7F
  shortname: wangjiezhe

utterances:
  enable: true
  repo: wangjiezhe/wangjiezhe.github.io
  issue_term: og:title
  # Available values: github-light | github-dark | preferred-color-scheme | github-dark-orange | icy-dark | dark-blue | photon-dark | boxy-light
  theme: github-light

discussbot:
  enable: true
  siteid: DTO-cxcp
  number: 5
  color: 3DA0F0
  dislikes: 1
  outlined: 1

# ---------------------------------------------------------------
# Post Widgets & Content Sharing Services
# ---------------------------------------------------------------

# ---------------------------------------------------------------
# Statistics and Analytics
# ---------------------------------------------------------------

google_analytics:
  tracking_id: UA-48537410-1

busuanzi_count:
  enable: true

# ---------------------------------------------------------------
# Search Services
# ---------------------------------------------------------------

local_search:
  enable: true
  style: flat

# ---------------------------------------------------------------
# Chat Services
# ---------------------------------------------------------------

# ---------------------------------------------------------------
# Tags Settings
# ---------------------------------------------------------------

note:
  style: flat

# ---------------------------------------------------------------
# Animation Settings
# ---------------------------------------------------------------

motion:
  async: true

pace:
  enable: true
  theme: bounce

crash_cheat: false

click_love: true

#! ---------------------------------------------------------------
#! DO NOT EDIT THE FOLLOWING SETTINGS
#! UNLESS YOU KNOW WHAT YOU ARE DOING
#! ---------------------------------------------------------------

vendors:
  anime: //cdn.jsdelivr.net/npm/animejs@3.2.0/lib/anime.min.js
  fontawesome: //cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/css/all.min.css
  reading_progress: //cdn.jsdelivr.net/gh/theme-next/theme-next-reading-progress@1/reading_progress.min.js
  katex: //cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css
  pjax: //cdn.jsdelivr.net/gh/next-theme/pjax@0/pjax.min.js
  pace: //cdn.jsdelivr.net/npm/pace-js@1/pace.min.js
  pace_css: //cdn.jsdelivr.net/npm/pace-js@1/themes/purple/pace-theme-bounce.css

