markdown: kramdown
kramdown:
    input: GFM

permalink: /:year/:month/:title/

highlighter: rouge

paginate: 16

url: http://wangjiezhe.github.io

timezone: "Asia/Shanghai"

encoding: utf-8

author:
    name: "Wang Jiezhe"
    url: https://twitter.com/wangjiezhe

gems:
    - jemoji
    - jekyll-mentions
    - jekyll-redirect-from
    - jekyll-sitemap

github:
    repo: https://github.com/wangjiezhe/wangjiezhe.github.io

version: 1.0.0
